### PR TITLE
2021-01-15 E484K neuts

### PR DESCRIPTION
**Pull request by ajgreaney**
@jbloom I am making a draft pull request, which I believe cannot be merged until marked ready for review. This plots the neut data from 2021-01-15. Because these were run with a 12-dilution series instead of the usual 7, the x-axis for these is much wider than usual. It doesn't look very good to plot everything on a shared x-axis now, because the majority of the neut curves get really squished so you can't see the data clearly. I changed to `sharex=False`. I know we don't usually do this because it can be confusing to have different x-axis scales on neut curve facets, but I think this shows the data better. I can revert back if you disagree. 

Compare [shared x-axis](https://github.com/jbloomlab/SARS-CoV-2-RBD_MAP_HAARVI_sera/blob/2021-01-15_E484K_neuts/experimental_validations/mutant_neuts_files/mutant_neuts_34_0.png):
image

to [independent x-axes](https://github.com/jbloomlab/SARS-CoV-2-RBD_MAP_HAARVI_sera/blob/2021-01-15_E484K_neuts/experimental_validations/mutant_neuts_files/mutant_neuts_34_2.png):
image

### CODE REVIEW

**Comment by jbloom** [comment]
Sounds good. Let's just wait until revisions to worry about it more.

**Comment by ajgreaney** [comment]
To be merged before #40, which actually reverts everything back to a shared x-axis! 🤪

**Comment by ajgreaney** [comment]
@jbloom Can you approve this PR? I will then merge this one, then #40

**Review by jbloom — APPROVED** [review]
Looks good.

**Pull request merged**
